Fix double delete in RandGen
AgreeableDeerGames/GameBackbone pull request #256
Opened 2020-11-01 22:58 UTC by lavinrp

closes #255 
Requires #239 be closed first

Updates RandGen to use value semantics. This fixes some potential memory corruptions caused by using the default copy and move special members while owning raw pointers.

2020-11-07 20:08 UTC, gyurgyma requested changes
I like this fix. Simple and easy. Definitely need to understand what the compiler was telling us. We should discuss that before merging this. Also we need to remove the comment that was wrong.

2020-11-07 20:08 UTC, gyurgyma commented on GameBackbone/Include/GameBackbone/Util/RandGen.h
>  		// Everyone is going to have to compile this anyway with the same compiler as their project so they won't have issues.
This comment is now wrong.

2020-11-15 23:13 UTC, gyurgyma commented on Tests/Source/RandGenTests.cpp
> +
This isn't a copy. This comment is confusing. Let's go ahead and fix this naming and stuff.

2020-11-16 00:39 UTC, lavinrp commented on GameBackbone/Include/GameBackbone/Util/RandGen.h
>  		// Everyone is going to have to compile this anyway with the same compiler as their project so they won't have issues.
comment removed.

2020-11-16 00:39 UTC, lavinrp commented on Tests/Source/RandGenTests.cpp
> +
renamed.

2020-11-16 00:59 UTC, gyurgyma approved these changes

2020-11-16 01:09 UTC, merged