Feature/i216 compound sprite components
AgreeableDeerGames/GameBackbone pull request #262
Opened 2020-12-05 18:39 UTC by Christopher-Ochs

Replaced `InternalType` with `ComponentWrapper` :

- Implemented Iterator and associated functions.

- Created `getComponentsWithPriorty ` function, which returns components with a given priority.

- Created `getComponentPriorties ` function, which returns a vector of all component priorities.

- Created `getDataAs` function, which returns the component as a specified type. (Throws custom `bad_cast` exception)

CompoundSpriteTests :

- Created `areSpritesEquivalent` function, which will determine if two sprites are equivalent without using the equals operator.

- Added tests to test new functionality added in `ComponentWrapper`.

- Fixed other test cases that were disabled using new functionality.

This change Closes #216 .

2020-12-05 18:47 UTC, lavinrp commented on GameBackbone/Include/GameBackbone/Core/CompoundSprite.h
> +		/// @brief Initializes a new instance of the <see cref="CompoundSprite"/> class. Sets the initial position of the CompoundSprite to the passed value.
<see cref="CompoundSprite"/>

2020-12-05 18:52 UTC, lavinrp commented on GameBackbone/Include/GameBackbone/Core/CompoundSprite.h
> +		///		The copy constructor is needed to copy the internal vector.
`The copy constructor is needed to copy the internal vector.`
This really isn't useful for users.

2020-12-05 19:06 UTC, gyurgyma requested changes

2020-12-05 20:07 UTC, gyurgyma requested changes

2020-12-05 20:07 UTC, gyurgyma commented on GameBackbone/Include/GameBackbone/Core/CompoundSprite.h
> +		}
These functions should also be split into the cpp.

2020-12-12 17:40 UTC, gyurgyma approved these changes

2020-12-12 17:41 UTC, merged